import * as Schema from "effect/Schema";

import { ClientRequest__CodexResponseHandoffMode } from "./_generated/schema.gen.ts";

export type V2ThreadRealtimeStartParams = {
  readonly codexResponseHandoffChannelPrefixes?: {
    readonly [x: string]: ReadonlyArray<string>;
  } | null;
  readonly codexResponseHandoffMode?: ClientRequest__CodexResponseHandoffMode | null;
  readonly delegationAckFiller?: boolean | null;
  readonly outputModality: "audio";
  readonly realtimeEndInstructions?: string | null;
  readonly realtimeStartInstructions?: string | null;
  readonly threadId: string;
  readonly voice?: string | null;
  readonly transport: { readonly sdp: string; readonly type: "webrtc" };
  readonly version: "v2" | "v3";
};
export const V2ThreadRealtimeStartParams = Schema.Struct({
  codexResponseHandoffChannelPrefixes: Schema.optionalKey(
    Schema.Union([Schema.Record(Schema.String, Schema.Array(Schema.String)), Schema.Null]),
  ),
  codexResponseHandoffMode: Schema.optionalKey(
    Schema.Union([ClientRequest__CodexResponseHandoffMode, Schema.Null]),
  ),
  delegationAckFiller: Schema.optionalKey(Schema.Union([Schema.Boolean, Schema.Null])),
  outputModality: Schema.Literal("audio"),
  realtimeEndInstructions: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  realtimeStartInstructions: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  threadId: Schema.String,
  voice: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  transport: Schema.Struct({
    sdp: Schema.String.annotate({
      description:
        "SDP offer generated by a WebRTC RTCPeerConnection after configuring audio and the realtime events data channel.",
    }),
    type: Schema.Literal("webrtc").annotate({ title: "WebrtcThreadRealtimeStartTransportType" }),
  }).annotate({ title: "WebrtcThreadRealtimeStartTransport" }),
  version: Schema.Literals(["v2", "v3"]),
}).annotate({
  title: "ThreadRealtimeStartParams",
  description: "EXPERIMENTAL - start a thread-scoped realtime WebRTC session.",
});

export type V2ThreadRealtimeStartResponse = {};
export const V2ThreadRealtimeStartResponse = Schema.Struct({}).annotate({
  title: "ThreadRealtimeStartResponse",
  description: "EXPERIMENTAL - response for starting thread realtime.",
});

export type V2ThreadRealtimeStopParams = { readonly threadId: string };
export const V2ThreadRealtimeStopParams = Schema.Struct({
  threadId: Schema.String,
}).annotate({
  title: "ThreadRealtimeStopParams",
  description: "EXPERIMENTAL - stop thread realtime.",
});

export type V2ThreadRealtimeStopResponse = {};
export const V2ThreadRealtimeStopResponse = Schema.Struct({}).annotate({
  title: "ThreadRealtimeStopResponse",
  description: "EXPERIMENTAL - response for stopping thread realtime.",
});
